language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
services:
- mongodb
script: gulp
before_install:
- openssl aes-256-cbc -K $encrypted_6ba402953e09_key -iv $encrypted_6ba402953e09_iv
  -in devConstants.js.enc -out ./server/config/devConstants.js -d
